create table
  public.resources (
    id bigint generated by default as identity,
    red_ml integer null default 0,
    green_ml integer null default 0,
    blue_ml integer null default 0,
    constraint potion_ml_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.potion_stock (
    id bigint generated by default as identity,
    red integer null,
    green integer null,
    blue integer null,
    dark integer null,
    name text null,
    sku text null,
    price text null,
    quantity integer null,
    type integer[] null,
    constraint potion_count_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.resources (
    id bigint generated by default as identity,
    red_ml integer null default 0,
    green_ml integer null default 0,
    blue_ml integer null default 0,
    dark_ml bigint null default '0'::bigint,
    gold bigint null,
    constraint potion_ml_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.carts_and_items (
    id integer generated by default as identity,
    quantity integer null,
    sku text null,
    constraint carts_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.carts_and_customers (
    id bigint generated by default as identity,
    name text null,
    class text null,
    level integer null,
    constraint carts_and_customers_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.cart_ledgers (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    cart_id bigint null,
    gold_change bigint null,
    red_change bigint null default '0'::bigint,
    green_change integer null default 0,
    blue_change integer null default 0,
    purple_change bigint null default '0'::bigint,
    teal_change bigint null default '0'::bigint,
    brown_change bigint null default '0'::bigint,
    constraint cart_ledger_entries_pkey primary key (id),
    constraint public_cart_ledger_entries_cart_id_fkey foreign key (cart_id) references carts_and_customers (id)
  ) tablespace pg_default;

  create table
  public.potion_ledgers (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    red_change bigint null default '0'::bigint,
    green_change bigint null,
    blue_change bigint null,
    purple_change bigint null,
    teal_change bigint null,
    brown_change bigint null,
    constraint potion_ledgers_pkey primary key (id)
  ) tablespace pg_default;

  create table
  public.resource_ledgers (
    id bigint generated by default as identity,
    created_at timestamp with time zone not null default now(),
    red_change bigint null default '0'::bigint,
    green_change bigint null,
    blue_change bigint null,
    gold_change bigint null,
    constraint resources_ledgers_pkey primary key (id)
  ) tablespace pg_default;